version: "2.3" #Задаем версию docker-compose.yml
services: #Задаем контейнеры
  nginx: #Задаем название первого контейнера - nginx и настраиваем его
    build: ./nginx #Указываем откуда будет вестись сборка
    ports: # Указываем какие порты нужно пробросить наружу
      - "80:80"
    volumes: #Подключаем рабочий каталог с кодом проекта
      - ./www:/var/www
    depends_on: #Устанавливаем последовательность загрузки контейнеров
      php: # php-контейнер запуститься раньше Nginx
        condition: service_healthy #Устанавливаем условия при котором запуститься контейнер nginx
    php: #Задаем название первого контейнера - php и настраиваем его
    build: ./php #Указываем откуда будет вестись сборка
    volumes: #Подключаем тот же рабочий каталог с кодом проекта
      - ./www:/var/www
    healthcheck: #Проверка работы приложения внутри контейнера
      test: ["CMD","php-fpm","-t"] #Команда теста, которую мы хотим выполнить
      interval: 3s #Интервал попыток запуска теста
      timeout: 5s #Отложенность запуска команды
      retries: 5 #Количество повторений
      start_period: 1s #Через сколько стартовать тест после запуска контейнера
