---
- name: мой новый плейбук  - Переменные - Debug, Set_fact, Register
  hosts: staging
  become: yes

  vars:
    message1: Privet
    message2: World
    secret: wrhnfgsdfnjfnasdjkfhnkjasdhnfjkasdnkjfhnUIOH

  tasks:
    - name: Print Secret vars DEBUG var
      debug: 
        var: secret
    - debug: 
        msg: "Секретное слово: {{ secret }}"
    - debug:
        msg: "Владелец этого сервера -->{{ owner }}<--"