---
- name: Установить или удалить postfix
  hosts: staging
  become: yes
  
  tasks:
  - name: Add the user 'user1'
    user:
      name: user1
      comment: Задание B6.5.1
      group: root
      #append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/user1/.ssh/id_rsa.pub