version: "3.3"

services:
 app:
   build:
     context: ..
     dockerfile: docker/Dockerfile
     target: builder
     args: &build_args
       GIT_COMMIT_BRANCH: 'local_branch'
       GIT_COMMIT_TAG: 'local_tag'
       GIT_COMMIT_SHORT_SHA: 'local_short_sha'
   env_file:
     — ./../.env.test
   depends_on:
     postgres:
       condition: service_healthy
   logging: *logging
   command: mvn test-compile failsafe:integration-test failsafe:verify

 postgres:
   image: postgres:12.2
   env_file:
     — ./../.env.test
   environment:
     POSTGRES_DB: test
     POSTGRES_USER: test
     POSTGRES_PASSWORD: password
     POSTGRES_PORT: 5432
   logging: *logging
   volumes:
       — ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
   healthcheck:
     test: ["CMD-SHELL", "! pgrep init"]
     interval: 5s
     timeout: 5s
     retries: 20