---
# tasks file for sf-ws-users
  - name: Добавить пользователя 'aaadm' с добавлением его в группу 'sudo'.
    user:
      name: aaadm
      password: aaadm
      #password: <хэш пароля пользователя 'aaadm'. Ansible вернет сообщение с ошибкой, если просто указать пароль>
      #shell: /bin/bash
      groups: sudo
      append: yes

  - name: Создать 2048-битовый SSH ключ для aaadm в ~aaadm/.ssh/id_rsa
    user:
      name: aaadm
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Установить authorized key из файла id_rsa.pub
    authorized_key:
      user: aaadm
      state: present
      key: "{{ lookup('file', '/home/aaadm/.ssh/id_rsa.pub') }}"