---
# tasks file for dnsmasq
#- name: install dnsmasq
#  apt:
#    name: dnsmasq
#    state: present
#
#- name: edit dnsmasq.conf no-dhcp-interface=
#  ansible.builtin.lineinfile:
#    path: /etc/dnsmasq.conf
#    regexp: '#no-dhcp-interface='
#    line: 'no-dhcp-interface=eth0'
#
#- name: edit dnsmasq.conf listen-address
#  ansible.builtin.lineinfile:
#   path: /etc/dnsmasq.conf
#    regexp: '#listen-address='
#    line: 'listen-address=127.0.0.1#5400'
#
#- name: edit dnsmasq.conf cache-size=
#  ansible.builtin.lineinfile:
#    path: /etc/dnsmasq.conf
#    regexp: '#cache-size=150'
#    line: cache-size=10001
#
#- name: edit dnsmasq.conf no-negcache
#  ansible.builtin.lineinfile:
#    path: /etc/dnsmasq.conf
#    regexp: '#no-negcache'
#    line: no-negcache
#
#- name: start and enable service
#  service:
#    name: dnsmasq
#    state: stopped
#    enabled: no
#
##- name: start and enable service
##  service:
##    name: dnsmasq
##    state: started
##    enabled: true

- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq





