---
#tasks file for dnsmasq

- name: Install dnsmasq
  package:
    name: dnsmasq
    state: latest

- name: Set configuration file
  template:
    src: dnsmasq.j2
    dest: /etc/dnsmasq.conf
    #validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes