---
- name: install apache and upload my web page
  hosts: staging
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html
    source_folder: ./MyWebSite2
    destin_folder: /var/www/html

  tasks:
  - name: Check OS 
    debug: var=ansible_os_family

  - block:   # REDHAT

      - name: Install Apache2 web server REDHAT
        yum: name=httpd state=latest 
      
      - name: Start web server and enable it REDHAT
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"


  - block:   # DEBIAN
      - name: install apache web server DEBIAN
        apt: name=apache2 state=latest

      - name: start web server and enable it DEBIAN
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - name: copy mysite to servers
#   copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    copy: src={{ item }} dest={{ destin_folder }} mode=0555
    with_fileglob: "{{ source_folder }}/*.*"

#    loop:
#      - "index.html"
#      - "index1.html"
#      - "index2.html"
    notify: 
      - Restart Apache2 RedHat
      - Restart Apache2 Debian
  handlers:
  
  - name: Restart Apache2 RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart Apache2 Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"