---
- hosts: "{{ HOSTS }}"
  become: true
  vars:
    owner: xhronx
  tasks:

  - name: Create "docker" group
    group:
      name: "{{ docker_group }}"
      state: present

  - name: Add remote "ubuntu" user to "docker" group
    user:
      name: "{{ remote_user }}"
      group: "{{ docker_group }}"
      append: yes
