---
# tasks file for sf-ws-nginx
- name: install nginx
  apt: 
    name: nginx
    state: latest
  notify: 
    - nginx run

- name: copy index
  template: 
    src: templates/index.html
    dest: /var/www/html/index.html
  notify: 
    - nginx restart

- name: 9000 порт to php
  template: 
    src: templates/default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: 
    - nginx restart