version: "3.3"

 # Вынести logging в YAML anchor и добавить его в 
 # сервисы web и redis.
x-logging: &logging
  driver: "json-file"
  options:
    max-size: "1000m"
    max-file: "1"

services:
  web:
    build: .
     # Вынести внешний порт web сервиса в .env файл 
     # и задать порт по умолчанию.
    ports:
      - "127.0.0.1:${WEB_OUTPORT}:5000"
    depends_on:
    - redis
      condition: service_healthy
    restart: unless-stopped
    networks:
    - net
     # Вынести logging в YAML anchor и добавить его в 
     # сервисы web и redis.
    logging: *logging

  redis:
    image: "redis:alpine"
    volumes:
    - redis-data:/data
    networks:
    - net
     # Создать profile только с redis базой.
    profiles:
      - db
     # Вынести logging в YAML anchor и добавить его в 
     # сервисы web и redis.
    logging: *logging
     # Ограничить ресурсы для redis сервиса, 
     # вынести значения в .env файл.
    deploy:
     resources:
       limits:
         cpus: "${DOCKER_WEB_CPUS:-0}"
         memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
networks:
 net:

volumes:
 redis-data:

